version: "3.8"

services:
  server-inversify-client-api:
    image: server-inversify-client-api:latest
    build:
      context: ./
      target: dev
      dockerfile: Dockerfile
    container_name: server.inversify.client.api
    depends_on:
      - mongodb-inversify-client-api
    expose:
      - '8001'
    volumes:
      - .:/dist
    command: pm2-runtime ./dist/servers/inversify.client.api/index.js -i max
    ports:
      - "8001:8001"
      - "9229:9229"
    environment:
      NODE_ENV: development
      MONGODB_URI: mongodb://mongodb-inversify-client-api:27017/inversify-client-api
    networks:
      - api_db_network

  mongodb-inversify-client-api:
    image: mongo:latest
    container_name: mongodb.inversify.client.api
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - api_db_network

volumes:
  mongodb_data:

networks:
  api_db_network:
    external: true