version: "3.8"

services:
  sqs-listener:
    image: sqs-listener:latest
    build:
      context: ./
      target: dev
      dockerfile: Dockerfile
    container_name: sqs.listener
    expose:
      - '4000'
    volumes:
      - .:/dist
    command: npm start
    environment:
      NODE_ENV: development
    networks:
      - api_db_network

networks:
  api_db_network:
    external: true